version: "3"

services:
  app:
    build: .
    command: npm start
    ports: 
      - "3000:3000"
    volumes:
      - .:/usr/app

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: newsletter
